// <auto-generated />
namespace Mocanu.Migrations.Catering
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditNew113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditNew113));
        
        string IMigrationMetadata.Id
        {
            get { return "201901161626439_EditNew113"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
